SystemOrganization addCategory: #'Magritte-Tests-Model-Utility'!
SystemOrganization addCategory: #'Magritte-Tests-Model-Description'!
SystemOrganization addCategory: #'Magritte-Tests-Model-Models'!
SystemOrganization addCategory: #'Magritte-Tests-Model-Memento'!
SystemOrganization addCategory: #'Magritte-Tests-Model-Mocks'!
SystemOrganization addCategory: #'Magritte-Tests-Model-Core'!
SystemOrganization addCategory: #'Magritte-Tests-Model-Accessor'!
